Forum/Organizations/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import StringField,SubmitField, PasswordField, BooleanField

class OrgRegistrationForm(FlaskForm):
    name = StringField('Organization name', validators=[DataRequired()])
    email = StringField('Organization email', validators=[DataRequired()])
    telephone  = StringField('Telephone Number', validators=[DataRequired()])
    website = StringField('Website link', validators=[])
    location = StringField('Location', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    image = FileField('Company Logo', validators=[ FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Submit')    


class OrgLoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()]) 
    password = PasswordField('Password', validators=[DataRequired()]) 
    remember_me = BooleanField('Remember me?')
    submit = SubmitField('Submit')

Forum/Bursary/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from Forum.Bursary.forms import BursaryForm
from flask_login import login_required, current_user
from Forum.models import Bursary
from Forum import db
from Forum.Utility.utils import SaveDocuments, page_permission

 
bursary = Blueprint('Bursary', __name__)


@bursary.route('/bursaries/add', methods = ['POST', 'GET'])
@login_required
@page_permission
def addBursary():
    form = BursaryForm()

    if form.validate_on_submit():
        doc = None
        if form.document.data:
            doc_obj = SaveDocuments()
            doc = doc_obj.save_bursary_document(form.document.data)


        _bursary = Bursary(
            bursary_name = form.bursary_name.data,
            web_link = form.web_link.data,
            open_date = form.opening_date.data,
            closing_date = form.closing_date.data,
            requirement_to_apply = form.requirements.data,
            how_to_apply = doc,
            document = form.document.data,
            company_id = current_user.id
        )
        db.session.add(_bursary)
        db.session.commit()
        return redirect(url_for('Organization.organization_profile', id = current_user.id))

    return render_template('Bursary/bursary_add.html',form = form, title = 'Add Bursary')


@bursary.route('/bursaries')
@bursary.route('/bursaries/')
@login_required
def showBursary():
    bursaries = Bursary.query.all()
    return render_template('Bursary/bursaries_show.html', title='Bursaries', bursaries = bursaries)

@bursary.route('/bursaries/<int:id>')
@bursary.route('/bursaries/<int:id>/')
@login_required
def infoBursary(id):
    return render_template('comming_soon.html')

Forum/Job/routes.py
from flask import Flask, Blueprint, abort,url_for, render_template, redirect, session
from Forum.models import Job
from Forum.Job.forms import JobForm
from Forum import db, bcrypt
from flask_login import current_user, login_required
from Forum.Utility.utils import page_permission 

job = Blueprint('Job', __name__)


@job.route('/jobs/add/', methods = ['POST', 'GET'])
@job.route('/jobs/add', methods = ['POST', 'GET'])
@login_required
@page_permission
def addJob():

    form = JobForm()
    if form.validate_on_submit():
        _job = Job(
            job_title = form.job_title.data,
            open_date = form.open_date.data,
            closing_date = form.closing_date.data,
            job_type = form.job_type.data,
            required_skills = form.requirements.data,
            job_description = form.job_description.data,
            sector = " ",
            duration = "  ", 
            job_link = form.job_link.data,
            city = form.city.data,
            province = form.province.data,
            company_id = current_user.id
        )

        db.session.add(_job)
        db.session.commit()
        return redirect(url_for('Organization.organization_profile', id=current_user.id))
    return render_template('Job/job_add.html', title = 'Post Job', form=form)


@job.route('/jobs', methods = ['POST', 'GET'])
@job.route('/jobs/', methods = ['POST', 'GET'])
@login_required
def show_Jobs():
    jobs = Job.query.all()

    return render_template('Job/jobs_show.html', title='Available Jobs', jobs = jobs)


@job.route('/job/<int:id>', methods = ['POST', 'GET'])
@job.route('/job/<int:id>/', methods = ['POST', 'GET'])
@login_required
def job_info(id):
    jobs = Job.query.get_or_404(id)

    return render_template('Job/job_info.html', title='Job Info', jobs = jobs)

Forum/Main/routes.py
from flask import Blueprint,render_template, redirect, url_for, request
from flask_login import current_user, login_required
from Forum.models import Post, User

main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('index.html')



@main.route('/home')
@login_required
def home():
    if current_user.is_authenticated:
        posts = current_user.followed_user_posts()
    else:
        posts = Post.query.order_by(Post.date_created.desc()).all()
    return render_template('home.html', title = 'Student Forum', posts = posts)


@main.route('/about')
def about():
    return 'the about page'

Forum/Organizations/routes.py
from flask import  Blueprint, session, url_for, render_template, redirect, abort
from Forum.Organizations.forms import OrgRegistrationForm, OrgLoginForm
from Forum.models import Organization, Job, Bursary, Residence
from Forum import db, bcrypt
from flask_login import login_required, login_user, logout_user, current_user
from Forum.Utility.utils import format_email, SaveDocuments, page_permission

organization = Blueprint('Organization', __name__)


@organization.route('/organization')
def organization_home():
    return render_template('Organization/organization_home.html', title='Companies')



#                        Registration Section                       #

@organization.route('/organization/register', methods = ['POST', 'GET'])
def organization_registeration():
    form = OrgRegistrationForm()
    if form.validate_on_submit():
        image = 'default'
        if form.image.data:
            photo = SaveDocuments()
            image = photo.save_organization_picture(form.image.data)
        name = form.name.data
        email = format_email(form.email.data)
        telephone  = form.telephone.data
        website = form.website.data
        location = form.location.data
        password = bcrypt.generate_password_hash(form.password.data)
        organization_info = Organization(name=name, email=email, telephone=telephone, website=website, location=location, password=password, image=image)
        
        db.session.add(organization_info)
        db.session.commit()
        return redirect(url_for('Organization.organization_login'))
    return render_template('Organization/organization_register.html', form = form, title='Organization Registration')



#                               LOGIN                                   #


@organization.route('/organization/login', methods=['POST', 'GET'])
def organization_login():

    if 'account_type' in session:
        if  session['account_type'] == 'Normal':
            return abort(401)


    form = OrgLoginForm()
    if form.validate_on_submit():
        session['account_type'] = 'Organization'
        user = Organization.query.filter_by(email = format_email(form.email.data)).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            return  redirect(url_for('Organization.organization_profile', id=user.id))
    return render_template('Organization/organization_login.html',form=form, title='Login Organization')


#                           LOGOUT 

@organization.route('/organization/logout')
@login_required
def organization_logout():
    logout_user()
    session.pop('account_type', None)
    return redirect(url_for('main.index'))


#                           Organization Profile                        # 

@organization.route('/organization/profile/<int:id>', methods=['POST', 'GET'])
@login_required
def organization_profile(id):
    user = Organization.query.get_or_404(id)
    bursaries = Bursary.query.filter_by(company_id = id)
    residences = Residence.query.filter_by(company_id = id)
    jobs = Job.query.filter_by(company_id = id)

    return render_template('Organization/organization_profile.html', title='Organization Profile', 
                        user=user, bursaries = bursaries, jobs = jobs, residences=residences)



@organization.route('/organization/account/<int:id>', methods=['POST', 'GET'])
@login_required
@page_permission
def organization_account(id):
    user = Organization.query.get_or_404(id)
    return render_template('Organization/organization_account.html', title='Organization Account', user=user)

Forum/templates/Organization/organization_account.html
{% extends 'layout.html' %}


{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}

<div class='container'>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">

            <div class="container-fluid">

                <a class="navbar-brand" href="{{ url_for('main.index') }}"> Student Forum </a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item"> <a class="nav-link" href="{{ url_for('Organization.organization_profile', id=current_user.id ) }}"> Profile </a> </li>
                        {% if current_user.offer_jobs %}
                            <li class="nav-item"> <a class="nav-link" href="{{ url_for('Job.addJob') }}"> Post Job </a> </li>
                        {% endif %}
                        {% if current_user.offer_bursary %}
                            <li class="nav-item"> <a class="nav-link" href="{{ url_for('Bursary.addBursary') }}"> Post Bursary </a> </li>
                        {% endif %}
                        {% if current_user.offer_residence %}
                            <li class="nav-item"> <a class="nav-link" href="{{ url_for('Bursary.addBursary') }}"> Post Bursary </a> </li>
                        {% endif %}
                        <li class="nav-item"> <a class="nav-link active" href="{{ url_for('Organization.organization_account', id=current_user.id) }}"> Account </a> </li>
                    </ul>
                    <ul class="navbar-nav justify-content-end">  
                        <li class="nav-item"> <a class="nav-link" href="{{ url_for('Organization.organization_logout') }}"> Logout </a> </li>
                    </ul>
                </div>
            </div>

        </nav>
    
</div>

<div class='container'>
    <br> <hr>

    <h3> {{ user.name }} </h3> <br>
     Email {{ user.email }}  <br>
     Telephone {{ user.telephone }}  <br>
     Website <a href="{{ user.website }}"> {{ user.website }} </a>  <br>
     Location {{ user.location }} <br>

</div>

<div>
    {% if current_user.offer_bursary %}
        <br> <hr>
        <h3> Bursaries Posted </h3>
    {% endif %}
    
</div>

<div>
    {% if current_user.offer_jobs %}
        <br> <hr>
        <h3> Jobs Posted </h3>
    {% endif %}
    
</div>


<div>
    {% if current_user.offer_residence %}
        <br> <hr>
        <h3> Residence Posted </h3>
    {% endif %}
    
</div>



{% endblock body %}

Forum/templates/Organization/organization_home.html
{% extends 'layout.html' %}


{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}
<div class='container'>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

            <div class="container-fluid">

                <a class="navbar-brand" href="{{ url_for('main.index') }}"> Student Forum </a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>


                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item"> <a class="nav-link" href="{{ url_for('Organization.organization_registeration') }}"> Register </a> </li>
                        <li class="nav-item"> <a class="nav-link" href="{{ url_for('Organization.organization_login') }}"> Login </a> </li>
                        <li class="nav-item"> <a class="nav-link" href="#"> Companies</a> </li>
                    </ul>
                    <ul class="navbar-nav justify-content-end">   
                        <li class="nav-item"> <a class="nav-link" href="#"> About us </a> </li>
                        <li class="nav-item"> <a class="nav-link" href="#"> Contacts </a> </li>
                    </ul>
                </div>
            </div>
        </nav>
</div>


<br> <hr>


<div>

    <p>
        Join us today 
    </p>

</div>


{% endblock body %}

Forum/templates/Organization/organization_login.html
{% extends 'layout.html' %}


{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}

    <div class='container'>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">

                <div class="container-fluid">

                    <a class="navbar-brand" href="{{ url_for('main.home') }}"> Student Forum </a>
                    
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item"> <a class="nav-link" href="{{ url_for('Organization.organization_registeration') }}"> Register </a> </li>
                            <li class="nav-item"> <a class="nav-link active" href="{{ url_for('Organization.organization_login') }}"> Login </a> </li>
                            <li class="nav-item"> <a class="nav-link" href="#"> About </a> </li>
                        </ul>
                    </div>
                </div>

            </nav>
        
    </div>


    <div>

        <br>
            <h3> Organization Login </h3>
        <br>

    </div>


    <div class='container'> 
        <form action="" method='POST'>

            {{ form.hidden_tag() }}


            {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control") }} <br>

            {% if form.email.errors %}
                {% for error in form.email.errors %}
                    <span> {{ error }} </span> <br>
                {% endfor %}
            {% endif %}
            
            {{ form.password.label(class="form-label") }}
            {{ form.password(class="form-control") }} <br>

            {% if form.password.errors %}
                {% for error in form.password.errors %}
                    <span> {{ error }} </span> <br>
                {% endfor %}
            {% endif %}

            

            <div class="form-check">
                {{ form.remember_me.label(class="form-check-label") }}
                {{ form.remember_me(class="form-check-input") }}
            </div>

            <br>
            
            {{ form.submit(class="btn btn-outline-primary") }} <br>
        </form>
    </div>

{% endblock body %}

Forum/templates/Organization/organization_profile.html
{% extends 'layout.html' %}


{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}

<div class='container'>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">

            <div class="container-fluid">

                <a class="navbar-brand" href="{{ url_for('main.index') }}"> Student Forum </a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item"> <a class="nav-link active" href="{{ url_for('Organization.organization_profile', id=current_user.id ) }}"> Profile </a> </li>
                        <li class="nav-item"> <a class="nav-link" href="{{ url_for('Job.show_Jobs') }}"> Jobs </a> </li>
                        <li class="nav-item"> <a class="nav-link" href="{{ url_for('Bursary.showBursary') }}"> Bursary </a> </li>
                        <li class="nav-item"> <a class="nav-link" href="{{ url_for('Organization.organization_account', id=current_user.id) }}"> Account </a> </li>
                    </ul>
                    <ul class="navbar-nav justify-content-end">  
                        <li class="nav-item"> <a class="nav-link" href="{{ url_for('Organization.organization_logout') }}"> Logout </a> </li>
                    </ul>
                </div>
            </div>

        </nav>
    
</div>

<div class='container'>
    <br> <hr>

    <h3> {{ user.name }} </h3> <br>
     Email {{ user.email }}  <br>
     Telephone {{ user.telephone }}  <br>
     Website <a href="{{ user.website }}"> {{ user.website }} </a>  <br>
     Location {{ user.location }} <br>
     About {{ user.about }} <br>

     <br>
     Total Jobs Posted {{ user.total_jobs_count() }} <br>
     Total Bursaries Posted {{ user.total_bursaries_count() }} <br>
     Total Residence Posted {{ user.total_residences_count() }}

</div>

<div>
    <br> <hr>
    <h3> Bursaries Posted </h3>

    {% if bursaries %}
        <ul>
            {% for bursary in bursaries %}
                <li> {{ bursary.bursary_name }} </li>
            {% endfor %}
        </ul>
    {% else %}
        No Bursary Posted yet
    {%  endif%}
    
</div>

<div>
    <br> <hr>
    <h3> Jobs Posted </h3>

    {% if jobs %}
        <ul>
            {% for job in jobs %}
                <li> {{ job.job_title }} </li>
            {% endfor %}
        </ul>
    {% else %}
        No Job Posted Posted yet
    {%  endif%}
    
</div>




{% endblock body %}

Forum/templates/Organization/organization_register.html
{% extends 'layout.html' %}


{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}

    <div class='container'>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

                <div class="container-fluid">

                    <a class="navbar-brand" href="{{ url_for('main.index') }}"> Student Forum </a>
                    
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>


                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item"> <a class="nav-link" href="{{ url_for('Organization.organization_registeration') }}"> Register </a> </li>
                            <li class="nav-item"> <a class="nav-link" href="{{ url_for('Organization.organization_login') }}"> Login </a> </li>
                            <li class="nav-item"> <a class="nav-link" href="#"> Companies</a> </li>
                        </ul>
                        <ul class="navbar-nav justify-content-end">   
                            <li class="nav-item"> <a class="nav-link" href="#"> About us </a> </li>
                            <li class="nav-item"> <a class="nav-link" href="#"> Contacts </a> </li>
                        </ul>
                    </div>
                </div>
            </nav>
    </div>

    <br><hr>

    <div class='container' >

        <div class="mb-3">

            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.hidden_tag() }}

                {{ form.name.label(class="form-label") }}
                {{ form.name(class="form-control") }} <br>

                {% if form.name.errors %}
                    {% for error in form.name.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}

                {{ form.email.label }}
                {{ form.email(class="form-control") }} <br>

                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}


                {{ form.telephone.label(class="form-label") }}
                {{ form.telephone(class="form-control") }} <br>

                {% if form.telephone.errors %}
                    {% for error in form.telephone.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}


                {{ form.website.label(class="form-label") }}
                {{ form.website(class="form-control") }} <br>

                {% if form.website.errors %}
                    {% for error in form.website.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}


                {{ form.location.label(class="form-label") }}
                {{ form.location(class="form-control") }} <br>

                {% if form.location.errors %}
                    {% for error in form.location.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}


                {{ form.image.label(class="form-label") }}
                {{ form.image(class="form-control") }} <br>

                {% if form.image.errors %}
                    {% for error in form.image.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}


                {{ form.password.label(class="form-label") }}
                {{ form.password(class="form-control") }} <br>

                {% if form.password.errors %}
                    {% for error in form.password.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}


                {{ form.confirm_password.label(class="form-label") }}
                {{ form.confirm_password(class="form-control") }} <br>

                {% if form.confirm_password.errors %}
                    {% for error in form.confirm_password.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}


                {{ form.submit(class="btn btn-outline-primary") }}

            </form> 
        </div>
    </div>


{% endblock body %}