Forum/Bursary/forms.py
from flask_wtf import  FlaskForm
from wtforms import StringField, SubmitField, SelectField, TextAreaField, IntegerField
from wtforms.validators import DataRequired, Email, URL, Optional, Length
from flask_wtf.file import FileAllowed, FileField
from wtforms.widgets.html5 import URLInput

from wtforms.fields.html5 import DateField
 
class BursaryForm(FlaskForm):
    web_link = StringField('Website Link', validators=[DataRequired()])
    bursary_name = StringField('Bursary Name', validators=[DataRequired()])
    opening_date = DateField('Open date', format='%Y-%m-%d')
    closing_date = DateField('Close date', format='%Y-%m-%d')
    requirements = TextAreaField('Requirements', validators=[DataRequired()])
    how_to_apply = TextAreaField('How to apply', validators=[DataRequired()])
    document = FileField('Bursary Document', validators = [FileAllowed(['pdf','doc', 'docx']), Optional()])
    submit = SubmitField('Submit')
 

Forum/Bursary/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from Forum.Bursary.forms import BursaryForm
from flask_login import login_required, current_user
from Forum.models import Bursary
from Forum import db
from Forum.Utility.utils import SaveDocuments, page_permission

 
bursary = Blueprint('Bursary', __name__)


@bursary.route('/bursaries/add', methods = ['POST', 'GET'])
@login_required
@page_permission
def addBursary():
    form = BursaryForm()

    if form.validate_on_submit():
        doc = None
        if form.document.data:
            doc_obj = SaveDocuments()
            doc = doc_obj.save_bursary_document(form.document.data)


        _bursary = Bursary(
            bursary_name = form.bursary_name.data,
            web_link = form.web_link.data,
            open_date = form.opening_date.data,
            closing_date = form.closing_date.data,
            requirement_to_apply = form.requirements.data,
            how_to_apply = doc,
            document = form.document.data,
            company_id = current_user.id
        )
        db.session.add(_bursary)
        db.session.commit()
        return redirect(url_for('Organization.organization_profile', id = current_user.id))

    return render_template('Bursary/bursary_add.html',form = form, title = 'Add Bursary')


@bursary.route('/bursaries')
@bursary.route('/bursaries/')
@login_required
def showBursary():
    bursaries = Bursary.query.all()
    return render_template('Bursary/bursaries_show.html', title='Bursaries', bursaries = bursaries)

@bursary.route('/bursaries/<int:id>')
@bursary.route('/bursaries/<int:id>/')
@login_required
def infoBursary(id):
    return render_template('comming_soon.html')

Forum/templates/Bursary/bursaries_show.html
{% extends 'layout.html' %}


{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}

    <div>
        {% if bursaries %}
            {% for bursary in bursaries %}
                <ul>
                    <li>

                    Offered by: <a href="{{ url_for('Organization.organization_profile', id=bursary.organization.id) }}"> {{ bursary.organization.name }} </a> <br>
                    <a href="{{ url_for('Bursary.infoBursary', id=bursary.id ) }}">  {{ bursary.bursary_name }} </a> <br>
                    Open date {{ bursary.open_date.strftime('%d-%m-%-Y') }} <br>
                    Closing date {{ bursary.closing_date.strftime('%d-%m-%-Y') }}
                    </li>
                    <br>
                </ul>
            {% endfor %}
        {% endif %}

    </div>


    <div>
        
    </div>

{% endblock body %}

Forum/templates/Bursary/bursary_add.html
{% extends 'layout.html' %}


{% block title %}
    {{ title }}
{% endblock title %}

{% block body %} 



    <div>
        <h3> Bursary Information </h3>
    </div>

    <div class='container'>
        <div class="mb-3">
            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                
                

                {{ form.bursary_name.label(class="form-label") }}
                {{ form.bursary_name(class="form-control") }} <br>

                {% if form.bursary_name.errors %}
                    {% for error in form.bursary_name.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}

                {{ form.opening_date.label(class="form-label") }}
                {{ form.opening_date(class="form-control") }} <br>

                {% if form.opening_date.errors %}
                    {% for error in form.opening_date.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}

                {{ form.closing_date.label(class="form-label") }}
                {{ form.closing_date(class="form-control") }} <br>

                {% if form.closing_date.errors %}
                    {% for error in form.closing_date.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}

                {{ form.requirements.label(class="form-label") }}
                {{ form.requirements(class="form-control")}} <br>

                {% if form.requirements.errors %}
                    {% for error in form.requirements.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}

                {{ form.how_to_apply.label(class="form-label") }}
                {{ form.how_to_apply(class="form-control") }} <br>

                {% if form.how_to_apply.errors %}
                    {% for error in form.how_to_apply.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}

                {{ form.document.label(class="form-label") }}
                {{ form.document(class="form-control") }} <br>

                {% if form.document.errors %}
                    {% for error in form.document.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}

                {{ form.web_link.label(class="form-label") }}
                {{ form.web_link(class="form-control")}} <br>

                {% if form.web_link.errors %}
                    {% for error in form.web_link.errors %}
                        <span> {{ error }} </span> <br>
                    {% endfor %}
                {% endif %}

                {{ form.submit(class="btn btn-outline-primary") }} 
                
            </form>
        </div>
    </div>

{% endblock body %}

Forum/templates/Bursary/bursary_info.html
{% extends 'layout.html' %}


{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}

    <div>

    </div>


    <div>
        
    </div>

{% endblock body %}