Forum/Job/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import StringField,SubmitField,SelectField, PasswordField, TextAreaField

from wtforms.fields.html5 import DateField

class JobForm(FlaskForm):
    job_title = StringField('Job Title', validators=[DataRequired()])
    open_date = DateField('Open date', format='%Y-%m-%d')
    closing_date = DateField('Close date', format='%Y-%m-%d')
    job_type = SelectField('Category', choices=(['Apprenticeship', 'Internship', 'Part time', 'Full time']))
    requirements = TextAreaField('Requirements', validators=[])
    job_description = TextAreaField('Job description', validators=[])
    salary = StringField('Salary', validators=[])
    # Sector = 
   
    job_link = StringField('Job Link', validators=[])
    province = SelectField('Provinces', choices=([ 'Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', 'Limpopo', 'Mpumalanga', 'Northern Cape', 'North West', 'Western Cape']))
    city = StringField('City', validators=[])
    submit = SubmitField('Submit')

Forum/Job/routes.py
from flask import Flask, Blueprint, abort,url_for, render_template, redirect, session
from Forum.models import Job
from Forum.Job.forms import JobForm
from Forum import db, bcrypt
from flask_login import current_user, login_required
from Forum.Utility.utils import page_permission 

job = Blueprint('Job', __name__)


@job.route('/jobs/add/', methods = ['POST', 'GET'])
@job.route('/jobs/add', methods = ['POST', 'GET'])
@login_required
@page_permission
def addJob():

    form = JobForm()
    if form.validate_on_submit():
        _job = Job(
            job_title = form.job_title.data,
            open_date = form.open_date.data,
            closing_date = form.closing_date.data,
            job_type = form.job_type.data,
            required_skills = form.requirements.data,
            job_description = form.job_description.data,
            sector = " ",
            duration = "  ", 
            job_link = form.job_link.data,
            city = form.city.data,
            province = form.province.data,
            company_id = current_user.id
        )

        db.session.add(_job)
        db.session.commit()
        return redirect(url_for('Organization.organization_profile', id=current_user.id))
    return render_template('Job/job_add.html', title = 'Post Job', form=form)


@job.route('/jobs', methods = ['POST', 'GET'])
@job.route('/jobs/', methods = ['POST', 'GET'])
@login_required
def show_Jobs():
    jobs = Job.query.all()

    return render_template('Job/jobs_show.html', title='Available Jobs', jobs = jobs)


@job.route('/job/<int:id>', methods = ['POST', 'GET'])
@job.route('/job/<int:id>/', methods = ['POST', 'GET'])
@login_required
def job_info(id):
    jobs = Job.query.get_or_404(id)

    return render_template('Job/job_info.html', title='Job Info', jobs = jobs)

Forum/templates/Job/job_add.html
{% extends 'layout.html' %}


{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}

    <div>
        <h3> Job Upload </h3>
    </div>



    <form action="" method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}

        {{ form.job_title.label(class="form-label") }}
        {{ form.job_title(class="form-control") }} <br>


        {{ form.open_date.label(class="form-label") }}
        {{ form.open_date(class="form-control") }} <br>


        {{ form.closing_date.label(class="form-label") }}
        {{ form.closing_date(class="form-control") }} <br>


        {{ form.job_type.label(class="form-label") }}
        {{ form.job_type(class="form-select") }} <br>


        {{ form.requirements.label(class="form-label") }}
        {{ form.requirements(class="form-control") }} <br>

        
        {{ form.job_description.label(class="form-label") }}
        {{ form.job_description(class="form-control") }} <br>


        {{ form.salary.label(class="form-label") }}
        {{ form.salary(class="form-control") }} <br>


        {{ form.job_link.label(class="form-label") }}
        {{ form.job_link(class="form-control") }} <br>


        {{ form.province.label(class="form-label") }}
        {{ form.province(class="form-select") }} <br>


        {{ form.city.label(class="form-label") }}
        {{ form.city(class="form-control") }} <br>

        {{ form.submit(class="btn btn-outline-primary") }} <br>


    </form>

{% endblock body %}

Forum/templates/Job/job_info.html
{% extends 'layout.html' %}


{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}
    <div>
        {{ jobs.job_title }}
    </div>

{% endblock body %}

Forum/templates/Job/jobs_show.html
{% extends 'layout.html' %}


{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}

    <div>
        {% if jobs %}
        
            {% for job in jobs %}
                <ul>
                Offred by <a href="{{ url_for('Organization.organization_profile', id=job.id) }}"> {{ job.organization.name }} </a> <br>
                <a href="{{ url_for('Job.job_info', id = job.id) }}"> {{ job.job_title }} </a> <br>
                {{ job.job_type }} <br>
                {{ job.city }} <br>
                Open date {{ job.open_date.strftime('%b-%d-%Y') }} <br>
                Closing date {{ job.closing_date.strftime('%b-%d-%Y') }}
                </ul>
                <br>
            {% endfor %}
        {% endif %}
    </div>

{% endblock body %}