Forum/Users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, SubmitField, BooleanField, PasswordField, TextAreaField, SelectField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length
from Forum.models import User
from flask_login import current_user

class RegistrationForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=3, max=100)])
    email = StringField('Email', validators=[DataRequired(), Email()]) 
    gender = SelectField('Gender', choices=(['Female', 'Male', 'Other']))
    password = PasswordField('Password', validators=[DataRequired()]) 
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Submit')

    def validate_email(self, email):
        user = User.query.filter_by(email = email.data).first()
        if user:
            raise ValidationError('Email already exist')

    def validate_username(self, username):
        user = User.query.filter_by(username = username.data).first()
        if user:
            raise ValidationError('username already exist')
    

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()]) 
    password = PasswordField('Password', validators=[DataRequired()]) 
    remember_me = BooleanField('Remember me?')
    submit = SubmitField('Submit')


class UpdateProfileForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[])
    email = StringField('Email', validators=[DataRequired(), Email()]) 
    about_me = TextAreaField('About me', validators=[])
    school = StringField('School', validators=[])
    course = StringField('Course', validators=[])
    profile_picture = FileField('Profile picture', validators=[ FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Update')

    def validate_email(self, email):
        if current_user.email != email.data:
            user = User.query.filter_by(email = email.data).first()
            if user:
                raise ValidationError('Email already exist')

Forum/Bursary/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from Forum.Bursary.forms import BursaryForm
from flask_login import login_required, current_user
from Forum.models import Bursary
from Forum import db
from Forum.Utility.utils import SaveDocuments, page_permission

 
bursary = Blueprint('Bursary', __name__)


@bursary.route('/bursaries/add', methods = ['POST', 'GET'])
@login_required
@page_permission
def addBursary():
    form = BursaryForm()

    if form.validate_on_submit():
        doc = None
        if form.document.data:
            doc_obj = SaveDocuments()
            doc = doc_obj.save_bursary_document(form.document.data)


        _bursary = Bursary(
            bursary_name = form.bursary_name.data,
            web_link = form.web_link.data,
            open_date = form.opening_date.data,
            closing_date = form.closing_date.data,
            requirement_to_apply = form.requirements.data,
            how_to_apply = doc,
            document = form.document.data,
            company_id = current_user.id
        )
        db.session.add(_bursary)
        db.session.commit()
        return redirect(url_for('Organization.organization_profile', id = current_user.id))

    return render_template('Bursary/bursary_add.html',form = form, title = 'Add Bursary')


@bursary.route('/bursaries')
@bursary.route('/bursaries/')
@login_required
def showBursary():
    bursaries = Bursary.query.all()
    return render_template('Bursary/bursaries_show.html', title='Bursaries', bursaries = bursaries)

@bursary.route('/bursaries/<int:id>')
@bursary.route('/bursaries/<int:id>/')
@login_required
def infoBursary(id):
    return render_template('comming_soon.html')

Forum/Friends/routes.py
from flask import Blueprint, render_template, redirect, url_for
from Forum.models import User

friends = Blueprint('Friends', __name__)


@friends.route('/friends')
def meet_friends():
    friend  = User.query.all()

    return render_template('friends.html', title = 'Meet new Friends', friends = friend)

Forum/Market/routes.py
from flask import Blueprint, redirect, render_template, url_for
from Forum.models import Product, User, ProductComment, Product
from flask_login import current_user, login_required
from Forum.Market.forms import ProductForm
from Forum.Posts.forms import CommentForm
from Forum import db
from Forum.Utility.utils import SaveDocuments

market = Blueprint('market', __name__)

@market.route('/market')
@login_required
def market_place():
    product = Product.query.order_by(Product.date_created.desc()).all()
    return render_template('Market/market.html', title = 'Market', products = product)


@market.route('/sell', methods = ['POST', 'GET'])
@login_required
def sell():
    form = ProductForm()
    if form.validate_on_submit():
        pic = None
        if form.image.data:
            photo = SaveDocuments()
            pic = photo.save_product_picture(form.image.data)

        fname = form.name.data
        fcondition = form.condition.data
        fcategory = form.category.data
        fprice = form.price.data
        fdescription = form.description.data

        product = Product(product_name = fname, condition = fcondition, 
                        category = fcategory, price = fprice, description = fdescription,
                        seller_id = current_user.id, image = pic)
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('market.market_place'))
    return render_template('Market/sell.html', form = form, title = 'Sell')



@market.route('/market/product/<int:product_id>', methods = ['POST', 'GET'])
@login_required
def product(product_id):
    
    form = CommentForm()
    prodct = Product.query.get_or_404(product_id)
    comment = ProductComment.query.filter_by(product_id = product_id)
    
    if form.validate_on_submit():
        prod = ProductComment(content = form.content.data, user_id = current_user.id, product_id = prodct.id)
        db.session.add(prod)
        db.session.commit()
        return redirect(url_for('market.product', product_id = product_id))
        
    return render_template('Market/product.html', form = form, product=prodct, comments = comment)

Forum/Posts/routes.py
from flask import Blueprint
from flask import render_template, redirect, url_for, abort
from Forum.Posts.forms import PostForm, CommentForm
from Forum.Utility.utils import SaveDocuments
from Forum.models import Post, Comment
from Forum import db
from flask_login import current_user, login_required

posts = Blueprint('posts', __name__)

@posts.route('/post/<int:post_id>', methods = ['POST', 'GET'])
@login_required
def post(post_id):
    form = CommentForm()
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post_id = post_id)
    if form.validate_on_submit():
        comm = Comment(content = form.content.data, user_id = current_user.id, post_id = post_id)
        db.session.add(comm)
        db.session.commit()
        return redirect(url_for('posts.post', post_id = post_id))
    return render_template('Post/post.html', post = post, comments = comments, form = form)


@posts.route('/post/create_post/', methods = ['POST', 'GET'])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        pic = None
        if form.image.data:
            photo = SaveDocuments() 
            pic = photo.save_post_picture(form.image.data)

        post = Post(title = form.title.data,
                    content = form.content.data,
                    picture = pic,
                    user_id = current_user.id )

        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('Post/create_post.html', title = 'Create new post', form = form)


@posts.route('/post/update/<int:post_id>', methods = ['POST', 'GET'])
@login_required
def update_post(post_id):
    form = PostForm()

    post = Post.query.get(post_id)

    form.title.data = post.title
    form.content.data = post.content

    if form.validate_on_submit():
        current_user.title = form.title.data
        current_user.content = form.content.data
        db.session.add()
        return redirect(url_for('main.home'))
    return render_template('Post/update_post.html', form = form, post = post)


@posts.route('/post/delete/<int:post_id>')
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort
    else:
        db.session.delete(post)
    return redirect(url_for('main.home'))



# @posts.route('/post/comment/<int:post_id>', methods = ['POST', 'GET'])
# @login_required
# def post_comment(post_id):
#     form = CommentForm()

#     if form.validate_on_submit():
#         comment = Comment(content=form.content.data, user_id = current_user.id, post_id = post_id)
#         db.session.add(comment)
#         db.session.commit()
#         return redirect(url_for('posts.post', post_id = post_id))
#     return render_template('post_comment.html', form = form, title='Comment')

Forum/Users/routes.py
from flask import Blueprint, session, render_template, redirect, url_for, request, abort
from Forum.Users.forms import RegistrationForm, LoginForm, UpdateProfileForm
from Forum.models import User, Post
from Forum import db, bcrypt
from flask_login import login_user, logout_user, current_user, login_required
from Forum.Utility.utils import SaveDocuments, format_email
users = Blueprint('users', __name__)


@users.route('/register', methods = ['POST', 'GET'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(
            first_name = form.name.data,
            gender=form.gender.data,
            email = format_email(form.email.data),
            password = hashed_password 
        )
        db.session.add(user)
        db.session.commit()
        return  redirect(url_for('users.login'))
    return render_template('register.html', title = 'Registration', form = form)


@users.route('/login', methods = ['POST', 'GET'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        session['account_type'] = 'Normal'
        user = User.query.filter_by(email = format_email(form.email.data)).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            return  redirect(url_for('main.home'))
    return render_template('login.html', title = 'login', form = form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    session.pop('account_type', None)
    return redirect(url_for('main.index'))


@users.route('/account', methods = ['POST', 'GET'])
@login_required
def account():
    form = UpdateProfileForm()
    if request.method == 'GET':
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.email.data = current_user.email
        form.about_me.data = current_user.about_me
        form.course.data = current_user.course
        form.school.data = current_user.school

    elif request.method == 'POST':    
        if form.validate_on_submit():
            if form.profile_picture.data:
                pic = SaveDocuments()
                current_user.profile_picture = pic.save_profile_picture(form.profile_picture.data)

            current_user.first_name = form.first_name.data
            current_user.last_name = form.last_name.data
            current_user.email = form.email.data
            current_user.about_me = form.about_me.data
            current_user.school = form.school.data
            current_user.course = form.course.data

            db.session.commit()
            return redirect(url_for('users.account'))

    return render_template('User/account.html', title = 'Account', form = form)


@users.route('/profile/<int:user_id>', methods = ['GET'])
@login_required
def user_profile(user_id):
    user = User.query.get_or_404(user_id)
    user_posts = Post.query.filter_by(user_id = user_id)
    return render_template('User/profile.html', user = user, posts = user_posts)



@users.route('/profile/follow/<int:user_id>')
@login_required
def follow(user_id):
    user = User.query.get(user_id)
    if user and user == current_user:
        return "You cannot follow yourself"

    elif user is None:
        return redirect(url_for('home'))
    
    current_user.follow(user)
    db.session.commit()
    return redirect(url_for('users.user_profile', user_id = user_id))



@users.route('/profile/unfollow/<int:user_id>')
@login_required
def unFollow(user_id):
    user = User.query.get(user_id)

    if user and user != current_user:
        current_user.unfollow(user)
        db.session.commit()
        return redirect(url_for('users.user_profile', user_id = user_id))
    
    elif user == current_user:
        return "You cannot unfollow yourself"
    else:
        return "user not found"

Forum/templates/User/account.html
{% extends 'layout.html' %}


{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}

    <div class='container'>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">

                <div class="container-fluid">

                    <a class="navbar-brand" href="{{ url_for('main.home') }}"> Student Forum </a>
                    
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>


                    <div class="collapse navbar-collapse" id="navbarSupportedContent">

                        {% if current_user.is_authenticated %}

                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                                <li class="nav-item"> <a class="nav-link active" href="{{ url_for('users.account')}}"> Account </a> </li>
                                <li class="nav-item"> <a class="nav-link" href="{{ url_for('posts.create_post') }}"> create new post </a> </li>
                                <li class="nav-item"> <a class="nav-link" href="{{ url_for('users.logout') }}"> logout </a> </li>
                                <br class="nav-item">
                                <li class="nav-item"> <a class="nav-link" href="{{ url_for('market.market_place') }}"> Market </a> </li>
                                <li class="nav-item"> <a class="nav-link" href="{{ url_for('market.sell') }}"> Sell </a> </li>
                                <li class="nav-item"> <a class="nav-link" href="{{ url_for('Bursary.showBursary') }}"> Bursaries </a> </li>
                                <li class="nav-item"> <a class="nav-link" href="{{ url_for('Friends.meet_friends') }}"> Meet a Friend </a> </li>
                                <li class="nav-item"> <a class="nav-link" href="#"> Connect </a> </li>

                            </ul>
                        {% endif %}

                    </div>
                </div>

            </nav>
        
    </div>

    <div class="container">
        
        <!-- <img src="{{ url_for('static', filename='profile_pictures/' + current_user.profile_picture|string ) }} ">
        <br>
        <h1> {{ current_user.first_name }} </h1>

        {% if current_user.last_name %}
             {{ current_user.last_name }} 
            <br>
        {% endif %}
             {{ current_user.email }} 
        <br>

        <p> Following {{ current_user.followed.count() }} </p>
        <p> Followers {{ current_user.followers.count() }} </p> -->
    </div>


    <div class="card mb-3 bg-light mb-3" style="max-width: 800px;">
        <div class="row g-0">
          <div class="col-md-4">
            <!-- <img src="..." alt="..."> -->
            <a href="{{ url_for('users.user_profile', user_id = current_user.id) }}">
                <img class="rounded" height=250px width=250px src="{{ url_for('static', filename = 'profile_pictures/' + current_user.profile_picture) }}"> 
            </a>
          </div>
          
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><a href="{{ url_for('users.user_profile', user_id = current_user.id) }}"> {{ current_user.first_name }} </a> </h5>
              
              <p class="card-text">Last name: {{ current_user.last_name }}</p>
              <p class="card-text">Email: {{ current_user.email }}</p>
              <p class="card-text">About me: {{ current_user.about_me }}</p>
              <p class="card-text">School: {{ current_user.school }}</p>
              <p class="card-text">Course: {{ current_user.course }} </p>
              <p class="card-text">Joined on: {{ current_user.joindate.strftime('%b-%d-%Y') }}</p>
              <p class="card-text">Followers: {{ current_user.followed.count() }}</p>
              <p class="card-text">Following: {{ current_user.followers.count() }} </p>

            </div>
          </div>
        </div>
      </div>


    <br><hr>
    <div class='container'>
        

        <form action="" method="POST" enctype="multipart/form-data" >
            
            {{ form.hidden_tag() }}

            {{ form.first_name.label(class="form-label") }}
            {{ form.first_name(class="form-control") }} <br>

            {{ form.last_name.label(class="form-label") }}
            {{ form.last_name(class="form-control") }} <br>

            {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control") }} <br>
            
            {{ form.school.label(class="form-label") }}
            {{ form.school(class="form-control") }} <br>

            {{ form.course.label(class="form-label") }}
            {{ form.course(class="form-control") }} <br>
            
            {{ form.about_me.label(class="form-label") }}
            {{ form.about_me(class="form-control") }} <br>


            {{ form.profile_picture.label(class="form-label") }}
            {{ form.profile_picture(class="form-control") }} <br>

            {{ form.submit(class="btn btn-outline-primary")  }}
        </form>
    </div>

{% endblock body %}

Forum/templates/User/profile.html
{% extends 'layout.html' %}


{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}

    <div class='container'>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <!-- Displaying the website Name or logo -->
                <a class="navbar-brand" href="{{ url_for('main.home') }}"> Student Forum </a>     
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    {% if current_user.is_authenticated %}

                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                            <li class="nav-item"> <a class="nav-link" href="{{ url_for('users.account')}}"> Account </a> </li>
                            <li class="nav-item"> <a class="nav-link" href="{{ url_for('posts.create_post') }}"> create new post </a> </li>
                            <li class="nav-item"> <a class="nav-link" href="{{ url_for('users.logout') }}"> logout </a> </li>
                            <br class="nav-item">
                            <li class="nav-item"> <a class="nav-link" href="{{ url_for('market.market_place') }}"> Market </a> </li>
                            <li class="nav-item"> <a class="nav-link" href="{{ url_for('market.sell') }}"> Sell </a> </li>
                            <li class="nav-item"> <a class="nav-link" href="{{ url_for('Bursary.showBursary') }}"> Bursaries </a> </li>
                            <li class="nav-item"> <a class="nav-link" href="{{ url_for('Friends.meet_friends') }}"> Meet a Friend </a> </li>
                            <li class="nav-item"> <a class="nav-link" href="#"> Connect </a> </li>
                        </ul>
                    {% else %}
                        <ul>
                            <li> <a href="{{ url_for('users.register') }}"> Register </a> </li>
                            <li> <a href="{{ url_for('users.login') }}"> Login </a> </li>
                            <li> <a href="#"> About </a> </li>
                        </ul>
                    {% endif %}

                </div>
            </div>
        </nav>    
    </div>

    <br><hr>

    <section class="my-5">
        <div class="row">
            <div class="col-md-6 col-lg-4">
                <div class="card card-personal">
                    <img  class="card-img-top" src="{{ url_for('static', filename='profile_pictures/' + user.profile_picture ) }}">
                    <div class="card-body">
                        <a>
                        <h4 class="card-title title-one"> {{ user.first_name }} </h4>
                        </a>
                        <a>
                            {% if user.last_name %}
                                <h4 class="card-title title-one"> {{ user.last_name }} </h4>
                            {% endif %}
                        </a>
                        <p class="card-meta">Joined in {{ user.joindate.strftime('%b-%d-%Y') }}</p>
                        <p class="card-text">
                            {% if user.about %}
                                {{ user.about }}
                            {% endif %}  
                        </p>
                        <hr>
                        <a class="card-meta"><span><i class="fas fa-user"></i> 

                            {% if current_user != user %}
                                {% if current_user.is_following(user) %}
                                    <!-- show a follow user button if they a a user if  -->
                                    <ul> <a class="btn btn-outline-danger" href="{{ url_for('users.unFollow', user_id = user.id) }}">Unfollow </a> </ul> 
                                {% else %}
                                    <ul> <a class="btn btn-outline-primary" href="{{ url_for('users.follow', user_id = user.id) }}">Follow </a> </ul> 
                                {% endif %}
                            
                            </span></a>
                            <a class="card-meta"><span><i class="fas fa-user"></i> 
                                    <ul> <a class="btn btn-outline-success" href="#">Message </a> </ul> 
                            </span></a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <hr><br>
    {% for post in posts %}
        <div class="card gedf-card">
            <div class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="mr-2">
                            <!-- showing post author profile image small and rounded -->
                            <img class="rounded-circle" width="45" src="{{ url_for('static', filename='profile_pictures/' + user.profile_picture ) }}" alt="">
                        </div>
                        <div class="ml-2">
                            <!-- showing post author user name -->
                            <div class="h5 m-0"> {{ post.author.first_name }} </div>
                            <!-- showing the created date of the post   -->
                            <div class="h7 text-muted"> {{ post.date_created.strftime('%b-%d-%Y') }} </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="card-body">
                {% if post.picture %}
                <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                    <!-- showing post images and converting post name to string to avoid error while concatinating -->
                    <img src="{{ url_for('static', filename='post_pictures/' + post.picture|string ) }}" class="img-fluid" />
                    <a href="#!">
                      <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                    </a>
                </div>
                {% endif %}

                <a class="card-link" href="#">
                    <h5 class="card-title"> {{ post.title }} </h5>
                </a>

                <p class="card-text">
                    {{ post.content }}
                </p>
                <a href="{{ url_for('posts.post', post_id=post.post_id) }}" class="card-link"><i class="fa fa-comment"></i> Comment</a>
            </div>
        </div>
        <br>
    {% endfor %}

{% endblock body %}